### ISSUE TITLE
Plumber seems not be able to get the precise origin of entities.

### ISSUE THREAD

**Issue by wolfsmith520-github** [lasa01/Plumber#169]
It works fine in old version (https://github.com/lasa01/io_import_vmf/releases/tag/v0.6.9)
![image](https://github.com/lasa01/io_import_vmf/assets/67470569/17b4501c-ca38-433c-97eb-2fb31ba318de)
![image](https://github.com/lasa01/io_import_vmf/assets/67470569/1671cf31-cc67-4613-8488-562f3c4758a4)

New version is a lit bit buggy(https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta4)
![image](https://github.com/lasa01/io_import_vmf/assets/67470569/6cea389c-39c8-4c5a-8733-be09574a8e20)

**Comment by lasa01** [comment]
This should be fixed in the latest release candidate. The brush recentering was missing so the origins were not adjusted. The origin might not always be the same as the origin in hammer, since the actual center of the brush is used instead of that value, but it should now be consistent with io_import_vmf.
