### ISSUE TITLE
Wrong normal maps textures color space / Custom color space incompability

### ISSUE THREAD

**Issue by XyozaxeR** [lasa01/Plumber#177]
By default color space of normal maps is the same as any other texture, but normal maps store data and not color and custom color profiles will break normal maps like on this screenshot

**sRGB OETIF (Custom sRGB profile)**
![sRGB_OETIF](https://github.com/lasa01/Plumber/assets/59504001/b6126229-6ab7-45de-8ee9-b8ee5ce74188)
To fix this issuse color space must be "Non-Colour Data".

**Non-Colour Data**
![Non-Colour Data](https://github.com/lasa01/Plumber/assets/59504001/add04d10-4266-4463-88c2-645a18a93cb1)
Please make default color space (ONLY FOR NORMAL MAPS) "Non-Colour Data" because changing color space of every normal map is very tideous when there's thousands of materials and overall this is just how normal maps work.

**Comment by lasa01** [comment]
The color space of normal maps is set to Non-Color already. The issue is probably that you seem to have custom color profiles in Blender, and the "Non-Color" color space is renamed to "Non-Colour Data" so the addon cannot find the proper color space.

I don't think it's worth it to add kind of fixes for these on my side unfortunately. I'm not sure how exactly the custom profiles work in Blender, but I would suggest you use ones that do not rename the default profiles, or if it's possible, add a color space with the name "Non-Color" for compatibility.

**Comment by XyozaxeR** [comment]
Well, I'll try to fix it myself but if you will fix it the custom color space name is "Filmic Blender"

**Comment by XyozaxeR** [comment]
uh editing the color space config wasn't that hard after all

**Comment by XyozaxeR** [comment]
In case someone has the same problem with filmic blender or other color spaces heres the solution

1. You should edit the config.ocio in {version}/datafiles/colormanagement and duplicate the colorspace that represents non-color data and name it "Non-Color" ( I additionally copied it and named "Raw" but I dont think that is exactly necessary )

2. Import the map/model/material in a version of blender without having the color profiles installed ( because for me for some reason it only changed the color profile of detail textures if I did that on the version of blender with edited color profiles installed )

3. Copy and paste the whole map collection from version without custom color profiles to version with edited color profiles
